[buildPlans.BbConsole]
family = "BbConsole"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = false
noLigation = true

  [buildPlans.BbConsole.variants]
  inherits = "ss15"

[buildPlans.BbConsole.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.BbConsole.weights.Bold]
shape = 700
menu = 700
css = 700
