[managers.system]
items = [
    "go",
    "gcc",
    "g++",
    "python",
    "pip",
    "make",
    "valgrind",
    "gdb",
    "libasan",
    "libhwasan",
    "liblsan",
    "libubsan",
    "meson",
]

[managers.flatpak]
items = [
    "com.github.marhkb.Pods",
    "com.usebruno.Bruno",
    "org.gnome.Builder",
    "app.devsuite.Manuals",
    "org.gnome.GHex",
    "io.gitlab.liferooter.TextPieces",
]
