[managers.system]
items = [
    "go",
    "gcc",
    "g++",
    "python",
    "pip",
    "make",
    "valgrind",
    "gdb",
    "libasan",
    "libhwasan",
    "liblsan",
    "libubsan",
    "meson",
    "ansible",
]
