[managers.flatpak]
items = [
    "app.drey.KeyRack",
    "app.drey.Typewriter",
    "com.belmoussaoui.Authenticator",
    "com.belmoussaoui.Obfuscate",
    "com.github.finefindus.eyedropper",
    "com.github.flxzt.rnote",
    "com.github.johnfactotum.Foliate",
    "com.obsproject.Studio",
    "com.obsproject.Studio.Plugin.GStreamerVaapi",
    "com.obsproject.Studio.Plugin.Gstreamer",
    "com.obsproject.Studio.Plugin.OBSVkCapture",
    "com.usebottles.bottles",
    "io.github.flattool.Warehouse",
    "net.nokyan.Resources",
    "org.gnome.Boxes",
    "org.gnome.Decibels",
    "org.gnome.DejaDup",
    "org.gnome.Firmware",
    "org.gnome.NetworkDisplays",
    "org.gnome.Papers",
    "org.gnome.Showtime",
    "org.gnome.World.PikaBackup",
    "org.gnome.seahorse.Application",
    "page.tesk.Refine",
]
