add = "sudo dnf install #:?"
remove = "sudo dnf remove #:?"
sync = "sudo dnf check-update"
upgrade = "sudo dnf update"

plural_name = "system packages"

hook_name = "system_packages"

[config]
many_args = true
