imports = [
    "bootstrap",
    "creativity",
    "desktop",
    "development",
    "entertainment",
    "internet",
    "productivity",
    "utils",
]

[managers.system]
items = [
    "aerc",
    "git",
    "lazygit",
    "starship",
    "fzf",
    "neovim",
    "syncthing",
    "tmux",
]

[managers.cargo]
items = [
    "rebos",
]
