imports = [
    "bootstrap",
    "development",
    "misc",
]

[managers.system]
items = [
    "aerc",
    "fd",
    "bat",
    "chezmoi",
    "git",
    "git-subtree",
    "lazygit",
    "starship",
    "fzf",
    "neovim",
    "tmux",
    "emacs",
    "zoxide",
    "fish",
    "ghostty",
    "pgcli"
]

[managers.cargo]
items = [
    "rebos",
]
