imports = [
    "bootstrap",
    "development",
    "misc",
]

[managers.system]
items = [
    "aerc",
    "git",
    "lazygit",
    "starship",
    "fzf",
    "neovim",
    "tmux",
    "emacs",
    "zoxide",
]

[managers.cargo]
items = [
    "rebos",
]
